version: "2.3"

services:
  postgres:
    restart: always
    image: postgres:12-alpine    
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5432"
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_PASSWORD: hh
      POSTGRES_DB: hh
      POSTGRES_USER: hh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 30s
      timeout: 15s
      retries: 5

  hh-homework-backend:
    image: hh-homework-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  hh-homework-front:
    image: hh-homework-front
    restart: always
    depends_on:
      hh-homework-backend:
        condition: service_started
    ports:
      - "80:80"
    # links:
    #   - hh-homework-backend 

  # autoheal:
  #   restart: always
  #   image: willfarrell/autoheal
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=all
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock    