version: "2.3"

services:
  # Postgres Service
  postgres:
    image: postgres:10.7-alpine   
    restart: always 
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hh
      POSTGRES_DB: hh
      POSTGRES_USER: hh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Backend Service
  hh-homework-backend:
    image: hh-homework-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  # Frontend Service
  hh-homework-front:
    image: hh-homework-front
    restart: always
    depends_on:
      hh-homework-backend:
        condition: service_started
    ports:
      - "80:80"
